baseurl = "http://www.example.com"
title = "Tate Anderson"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Tate Anderson"
  info = "Worship Leader/Musician"
  description = "Tate Anderson's personal website"
  keywords = "blog,personal"
  avatarurl = "images/tateanderson_staff2023_pp copy.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "facebook"
  icon = "fa-brands fa-facebook-square fa-2x"
  weight = 1
  url = "https://www.facebook.com/tateaandy"
[[params.social]]
  name = "instagram"
  icon = "fa-brands fa-instagram fa-2x"
  weight = 2
  url = "https://www.instagram.com/tateaandy/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Portfolio"
  weight = 3
  url = "portfolio/"
  
[caches]
[caches.images]
   dir = ':cacheDir/images'